name: Test
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: dndred/test2
          fetch-depth: 0
          path: ../test2
      - run: touch ../test2/test.txt
      - run: cd ../test2 && ls -la
      - name: Pull Request
        uses: dndred/action-pull-request-another-repo@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_folder: 'test2'
          destination_repo: 'dndred/test2'
          destination_base_branch: 'master'
          destination_head_branch: 'test'
          user_email: 'dndred@gmail.com'
          user_name: 'dndred'
